### ISSUE TITLE
ubuntu 16.04 装上去之后撤回没有回应 

### ISSUE THREAD

**Issue by wanyvic** [ZKeeer/WeChatForRevocation#1]
装的python3.5 itchat xdg-utils 
撤回消息后没有提示，并且添加关键词也失败，提示“添加关键词失败，请重试”

**Comment by ZKeeer** [comment]
@wanyvic 你修改一下路径，我在windows下编辑是这样的“C:\\xxxxx”，linux下应该写成“/home/xxxx”

**Comment by XAS-712** [comment]
我记得现在路径编码没有问题了。Debian8.6完美运行
