### ISSUE TITLE
CPU占用33%左右, 能否优化? win10

### ISSUE THREAD

**Issue by yangyay** [ZKeeer/WeChatForRevocation#27]
CPU占用33%左右, 能否优化? win10

**Comment by XAS-712** [comment]
能提供一下使用的截图以及运行方式等吗？

**Comment by yangyay** [comment]
![image](https://user-images.githubusercontent.com/10424184/40230215-544df078-5ac9-11e8-9ec5-fc0fd7a5b404.png)
我是直接下载打包好的程序, 双击运行, 并未以管理权限运行.
运行截图:
![image](https://user-images.githubusercontent.com/10424184/40230289-99c5e20a-5ac9-11e8-8dd3-0b0f5ddf1f49.png)

**Comment by XAS-712** [comment]
也许是Win打包程序的锅？
我在Debian8上未见异常。。。
也不排除是部分冗余的模块占用资源。
@ZKeeer

**Comment by yangyay** [comment]
那怎么办?

**Comment by ZKeeer** [comment]
@yangyay 已经优化过，再试试新的release？^_^

**Comment by yangyay** [comment]
@ZKeeer 谢谢, 现在不占CPU了.
