### ISSUE TITLE
取得二维码后立刻自动退出

### ISSUE THREAD

**Issue by XAS-712** [ZKeeer/WeChatForRevocation#3]
在Debian8下，Py3.4.2，已安装itchat，打印了两行之后立即退出了

**Comment by ZKeeer** [comment]
@XAS-712 你好，有没有多次尝试，出现的结果是否都是未打印完就退出了？再者，有没有相关的log贴上来。

**Comment by XAS-712** [comment]
多次尝试，都是打印了完整的两行就退出，最后一行是说的下载二维码
我是用ssh连接的，会不会与这也有关？

**Comment by ZKeeer** [comment]
@XAS-712 我明白了，Main.py文件中，程序入口有条语句itchat.auto_login(hotReload=True)，用itchat.auto_login(hotReload=True, enableCmdQR=2)代替。Main.py稍后更新，正在想解决办法，目前只能这么处理。

**Comment by XAS-712** [comment]
是不是因为正常在图形界面下使用会在弹出二维码，而我是ssh？

**Comment by ZKeeer** [comment]
@XAS-712 对，正常图形界面，会使用默认的图片查看软件打开；使用命令行界面的话，只能将二维码打印到命令行输出。

**Comment by XAS-712** [comment]
我修改了代码，可以不需修改文件即可实现命令行输出，只需加-t参数即可，已提交pull request

**Comment by ZKeeer** [comment]
@XAS-712 稳！多谢老哥，还有什么好的idea欢迎一起搞事

**Comment by ZKeeer** [comment]
多谢，我拉下来测试下

**Comment by XAS-712** [comment]
很抱歉，之前提交的代码有些问题，现已重新提交pull request
