### ISSUE TITLE
相关环境安装无误，运行 main.py报错

### ISSUE THREAD

**Issue by wang0168** [ZKeeer/WeChatForRevocation#30]
~/WeChatAssistant# python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import itchat
ImportError: No module named 'itchat'
我是直接clone 下来的源码安装环境 运行的

系统版本：ubuntu 16.04
python 版本：3.5.2

**Comment by wang0168** [comment]
Requirement already satisfied: itchat in /usr/local/lib/python2.7/dist-packages (1.3.10)
Requirement already satisfied: pypng in /usr/local/lib/python2.7/dist-packages (from itchat) (0.0.18)
Requirement already satisfied: pyqrcode in /usr/local/lib/python2.7/dist-packages (from itchat) (1.2.1)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from itchat) (2.19.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->itchat) (2018.8.13)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->itchat) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->itchat) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->itchat) (2.7)

**Comment by ZKeeer** [comment]
> Requirement already satisfied: itchat in /usr/local/lib/python2.7/dist-packages (1.3.10)

你的模块都安装到2.7里面了，试试用pip3安装 @wang0168

**Comment by wang0168** [comment]
重新安装 pip3 现在可以了 感谢

**Comment by XAS-712** [comment]
部分系统环境下不会自动把pip映射到pip3，建议在文档中注明
